name: My workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hga
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: install bats
        run: npm install -g bats
      - name: run bats version
        run: bats -v
