name: My workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hga
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: install bats
        run: npm install -g bats
      - name: run bats version
        run: bats -v
      - name: validación de archivos YAML utilizando un esquema JSON remoto
        uses: mpoc/nexus-validate-using-remote-schema-action@v1
        with:
          api-endpoint: 'https://onlineyamltools.com/convert-yaml-to-json'
          yaml-file: my_workflow.yaml
